config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: "/", path_names: { sign_in: 'login', sign_out: 'logout', :sign_up => 'sign-up' }
  devise_scope :user do
   authenticated :user do
     root 'links#index', as: :authenticated_root
   end

   unauthenticated do
     root 'devise/registrations#new', as: :unauthenticated_root
   end
 end

 resources :links

get '/:slug' => 'visits#create'

end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  has_many :visits
  validates :slug, presence: true
validates :target_url, presence: true

  def standardize_target_url!
    self.target_url.gsub!("http://", "")
    self.target_url.gsub!("https://", "")
  end

  def visit_count
  self.visits.count 

    
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :links
end

app/models/visit.rb
class Visit < ActiveRecord::Base

belongs_to :link

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_out_path_for(resource_or_scope)
    links_path
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  
before_action :authenticate_user!
  
  def index
    @links = current_user.links
  end

  def show
    @link = current_user.links.find_by(:id => params[:id])

    unless @link
      flash[:warning] = "Link not found"
      redirect_to links_path
    end
  end


  def new
    @link = Link.new
  end

  def create 
    @link = current_user.links.new(params[:link])
      if @link.save
        flash[:success] = "Link created successfully"
        redirect_to links_path
      else
        render 'new'
      end
  end

  
  def edit
    @link = Link.find_by(:id => params[:id])
  end

  def update
    @link = Link.find_by(:id => params[:id])

      if @link.update(params[:link])
        @link.standardize_target_url!
        flash[:success] = "Link created successfully"
        redirect_to links_path
      else
        render 'edit'
    end
  end

  def destroy
    @link = Link.find_by(:id => params[:id])
    @link.destroy
    flash[:success] = "Link destroyed successfully"
  redirect_to links_path
  end

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

  def create
    @link = Link.find_by(:slug => params[:slug])
    
      if @link
        @link.visits.create(:ip_address => request.remote_ip)
        redirect_to "http://#{@link.target_url}"
      else
      raise ActionController::RoutingError.new('Not Found')
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name">
      <h1><a href="#">URL</a></h1>
    </li>
     <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
    <li class="toggle-topbar menu-icon"><a href="#"><span></span></a></li>
  </ul>

  <section class="top-bar-section">
    <!-- Right Nav Section -->
    <% if current_user.nil? %>
    <ul class="right">
      
      <li class="has-dropdown">
        <a href="#">Sign in</a>
        <ul class="dropdown">
          <li><a href="/sign-up">Create Account</a></li>
          <li><a href="/login">Login</a></li>
        </ul>
      </li>
    </ul>
<% end %>

<% if current_user %>
    <ul class="right">
      
      <li class="has-dropdown">
        <a href="#">Account</a>
        <ul class="dropdown">
          <li><a data-method="delete" rel="nofollow" href="/logout">Logout</a></li>
        </ul>
      </li>
    </ul>
<% end %>
    <!-- Left Nav Section -->
    <ul class="left">
      <li><a href="#">Left Nav Button</a></li>
    </ul>
  </section>
</nav>
<% flash.each do |name, message| %>

  <%= content_tag :div, message, class: "alert alert-#{name}" %>

<% end %>
    <%= yield %>
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/links/_form.html.erb
<div class="row">


<% if @link.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@link.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @link.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= simple_form_for @link do |f| %>
  <%= f.input :slug, required: :false %>
  <%= f.input :target_url %>
  <%= f.button :submit %>
<% end %>
</div>

app/views/links/edit.html.erb
<h2>Edit your links</h2>
<%= render "form" %>

app/views/links/index.html.erb
<div class="row">

<h1>Your links </h1>
<h2><small><%= link_to "Add New Link", new_link_path %></small></h2>

<table class="table table-striped table-hover">
  <tr>
    <th>Slug</th>
    <th>Target URL</th>
    <th>Created At</th>
    <th colspan="2">Actions</th>
    <th>Visits</th>
  </tr>
  <% @links.each do |link| %>
    <tr>
      <td><%= link_to link.slug, link_path(link.id) %></td>
      <td><%= link_to link.target_url, link_path(link.id) %></td>
      <td><%= link_to link.created_at, link_path(link.id) %></td>
      <td><%= link_to "Edit", edit_link_path(link.id) %></td> <td><%= link_to "Delete", link_path(link.id), :method => "delete", :data => {:confirm => "Are you sure you would like to delete the link: #{link.slug}?"} %>  </td>
      <td><%= link.visit_count %></td>

    </tr>
  <% end %>
</table>



</div>

app/views/links/new.html.erb
<h2>create a new link</h2>


<%= render 'form' %>

app/views/links/show.html.erb
<h1>Link Stats for <%= @link.slug%></h1>
<h3>Visits: <%= @link.visit_count %></h3>